### ISSUE TITLE
--folder-uri question

### ISSUE THREAD

**Issue by larshp** [microsoft/vscode-test-web#1]
Hi,
I'm trying to use the `--folder-uri` option to have files loaded at startup, currently using full URI:
https://github.com/larshp/vscode-source-map/blob/main/package.json#L49
and also tried multiple other formats

Are there any examples for using `--folder-uri` ?

**Comment by larshp** [comment]
looks like https://github.com/microsoft/vscode-test-web/commit/6fba67490a110cdafa3b6296b21e488bdc106b54 might solve my issue

**Comment by aeschli** [comment]
Now you can also specify a local folder with test data:

```
vscode-test-web --browserType=chromium --extensionDevelopmentPath=$extensionLocation $testDataLocation
```

VS Code Browser will open on a virtual workspace (`vscode-test-web://mount`). A  file system provider will fetch the file/folder data from the local disk. Changes to the file system are kept in memory and are not written back to disk.

The `--folder-uri` option is still available, but no longer documented.
It's still useful to test other file system providers, e.g. provided by your or another extension.
