### ISSUE TITLE
Using with gitpod.io

### ISSUE THREAD

**Issue by HKalbasi** [microsoft/vscode-test-web#10]
I like to test vscode web extensions inside web browser using https://gitpod.io but I'm currently getting some mixed content errors. If this is the only problem, it should be fixed by [not hardcoding the protocol to `http`](https://github.com/gitpod-io/gitpod/issues/1005).

**Comment by aeschli** [comment]
Not sure how `vscode-test-web` can help you testing extensions in gitpod?
