### ISSUE TITLE
Requesting help with error 'Invalid regular expression: invalid group specifier name'

### ISSUE THREAD

**Issue by jgclark** [microsoft/vscode-test-web#12]
The MS team reached out to me to suggest updating the extension I maintain called 'jgclark.vscode-todo-highlight' (but didn't author) to work with the web version. The team member helped with a PR which I'm now trying to test.  I'm finding the documentation too sketchy for this novice. 

The best I can attempt is do the following from the extension's folder (running on macOS 11.3.1):
```zsh
npm i -D @vscode/test-web
npx vscode-test-web --browserType=webkit --extensionDevelopmentPath=. --folderPath=.
```
This spins up Playwright to the VSCode welcome screen. But there are no extensions loaded, nor can I see a way of loading a .vsix file which is the way I usually test a new build.

It gives me this error popup: `Activating extension 'jgclark.vscode-todo-highlight' failed: Invalid regular expression: invalid group specifier name`, but without any information in the Output or Error sections, I don't know how to start fixing this. Please advise

**Comment by aeschli** [comment]
There's no named parameter `--folderPath`, just add the path to open as argument
`npx vscode-test-web --browserType=webkit --extensionDevelopmentPath=. .`

`Activating extension 'jgclark.vscode-todo-highlight' failed: Invalid regular expression: invalid group specifier name` is the error that prevents your extension from being activated.
The regexp implementations of Node and the various browsers are slightly different. Your issue looks like 
https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

You can use the dev tools in the opened browser to debug this.

**Comment by jgclark** [comment]
Many thanks @aeschli for your help with these two points.
I thought the error report was about loading the extension, not something in the extension itself. I expect I can sort the regex based on your SO link.

**Comment by aeschli** [comment]
Closed the issue as it seems the problem is with the code of the todo-highlight extension.
