### ISSUE TITLE
Latest version of VSCode Insiders fails to load and execute tests

### ISSUE THREAD

**Issue by slavek-kucera** [microsoft/vscode-test-web#128]
Starting today I am unable to run tests in the web environment.
The latest VSCode Insiders version (34f8428e4b0e3bf822f4b9e8b4e3e0cab69ef2) does not load in the browser.
The console log contains a lot of "Duplicate definition of module" entries. Also the page tries to retrieve non-existent files from the server (/static/build/out/vs/platform/product/common/product.js, /static/build/out/vs/platform/window/common/window.js).

[Log is attached](https://github.com/user-attachments/files/16096837/insiders.log)

**Comment by thorsten-wolf-neptune** [comment]
I also experience an issue. Last week i bootstrapped my first web extension like mentioned here:
https://code.visualstudio.com/api/get-started/your-first-extension
I chose "Typescript Web Extension" and was able to test this with the provided npm script "run-in-browser". When i tried the same today (freshly created from the wizard) i just get a blank screen. There seem to be some files missing:
![image](https://github.com/microsoft/vscode-test-web/assets/83953375/027734d6-82bb-421c-a0dd-61181d07b007)
![image](https://github.com/microsoft/vscode-test-web/assets/83953375/c6274ce6-564c-4999-bf08-c16eba9adb69)

**Comment by slavek-kucera** [comment]
With today's version of the insiders build, the errors shifted to the following 
[localhost-1720430718020.log](https://github.com/user-attachments/files/16125522/localhost-1720430718020.log)

**Comment by pderaaij** [comment]
I am running into the same issues. Would be great if there is a solution.

**Comment by slavek-kucera** [comment]
VSCode issue.

**Comment by Frederisk** [comment]
Hi, I encountered the same problem recently, I browsed the issue here and used the stable version to temporarily solve the problem.

I noticed @slavek-kucera mentioned that this is an upstream issue from vscode insiders, however I didn't find the relevant issue tracker in the issue list there (probably due to too many issues for me to find it), can someone tell Where can I track the progress of this issue?

**Comment by slavek-kucera** [comment]
@Frederisk Make sure you are running 0.0.56
https://github.com/microsoft/vscode/issues/220171
