### ISSUE TITLE
Allow SharedArrayBuffer to be used by extensions

### ISSUE THREAD

**Issue by michalbali256** [microsoft/vscode-test-web#14]
Hi,

I am trying to make our extension (https://github.com/eclipse/che-che4z-lsp-for-hlasm) work in browser environment so it can be used with web version of vscode. It is written in C++ and we are using emscripten to compile it into WebAssembly. The C++ backend uses multiple threads, so in browser, we need full support of SharedArrayBuffer. That is only available, if cross origin isolation is enabled, see this: https://developer.chrome.com/blog/enabling-shared-array-buffer/

I have experimented with adding the headers from the blog to app.ts file, but as far as I understand, the extensionHost failed to start, since it is downloaded from a different site (vscode-webview.net). See the following error: 
![image](https://user-images.githubusercontent.com/38988507/142400444-7c948440-f65a-4a9e-ab37-e0865ec28181.png)

By the way, the extension compiled to WebAssembly seems to be running when I start chrome with --disable-web-security.

**Comment by aeschli** [comment]
Closing in favor of https://github.com/microsoft/vscode/issues/137884
