### ISSUE TITLE
FS mount stopped working in Insiders Web VSCode

### ISSUE THREAD

**Issue by asafamr** [microsoft/vscode-test-web#16]
I see a single FS node ("mount") in Firefox and Chrome
![image](https://user-images.githubusercontent.com/5182534/144394009-665c568f-9fed-4864-a513-4834a559c681.png)
to reproduce run `npm run run-in-browser` in https://github.com/asafamr/svelte-vscode-web/tree/7ab1757e6de482f3f57f6b2968cf9cc7dff2bfca

**Comment by cmumatt** [comment]
Same behavior observed on stable 1.63 now.  Currently working around this using --version=sources w/1.62 local.

**Comment by michalbali256** [comment]
This issue seems related https://github.com/microsoft/vscode/issues/139053

**Comment by cmumatt** [comment]
Appears to be working again on insider channel.

Version: 1.64.0-insider
Commit: e8a26d3ebf5095d4324ad4bf794787540ed3b33e
Date: 2021-12-21T05:20:38.543Z (15 hrs ago)
