### ISSUE TITLE
Testing extensions which access clipboard

### ISSUE THREAD

**Issue by whitphx** [microsoft/vscode-test-web#3]
Hi,

All tests in which the extension accesses the clipboard (via `vscode.env.clipboard`) fails.
When running in non-headless mode, the browser shows the prompt to ask users for the permission to access the clipboard, so I think this is the cause of the problem - it seems we have to permit accessing the clipboard during the tests anyway.

Are there any solutions or workarounds?

**Comment by aeschli** [comment]
I haven't looked into this.
I see there's a playwright API to grant permissions:
https://playwright.dev/docs/1.14/emulation#permissions

**Comment by aeschli** [comment]
Net release (0.0.14) has a new option `--permission` to grant the opened browser permissions such as access to the clipboard.

**Comment by whitphx** [comment]
Thank you very much!
