### ISSUE TITLE
No search provider registered for scheme: vscode-test-web

### ISSUE THREAD

**Issue by wkillerud** [microsoft/vscode-test-web#39]
Hello!

I'm working on a language server extension, and I've successfully added support for a web version. I'm having trouble adding tests though.

- The extension runs as expected on [vscode.dev by following the docs](https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension-in-on-vscode.dev)
- It also runs as expected in the [web extension host on desktop](https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension-in-vs-code-running-on-desktop)

I'd like to add some tests to avoid breaking it in the future, but the extension doesn't want to work when I run `vscode-test-web`. I've tracked the problem down to the error message from the issue title.

To reproduce:

- Check out [`repro/no-search-provider` on wkillerud/vscode-scss](https://github.com/wkillerud/vscode-scss/tree/repro/no-search-provider)
- `npm install`
- `npm run open:chrome`
- Open any SCSS-file, for instance `definition/main.scss`

At this point the extension starts up. As the Worker starts it will do a request to the [client which then calls `workspace.findFiles()`](https://github.com/wkillerud/vscode-scss/blob/082051f78bb2ad786bf6dcca39d429b1caed05e6/src/client/client.ts#L170-L177).

- View Output, pick Some Sass from the list.

Only the line `Running workspace.findFiles...` is visible. On `vscode.dev` both `log(...)` lines appear almost instantly.

- Open the developer tools Console
- Look for a line `WARN No search provider registered for scheme: vscode-test-web, waiting` (logged at the Info level if you use the in-browser filters).

I tried poking around in this repo to see if I could add a search provider, but I'm not sure where or how to proceed. Or is there something I'm missing in my extension?

**Comment by dselman** [comment]
I've the same issue in my web extension: onReady it tries to send search for files and send them via a custom message to a language server. The search code crashes when running in vscode-test-web (Chrome).

**Comment by wkillerud** [comment]
Fixed in [0.0.51](https://github.com/microsoft/vscode-test-web/releases/tag/v0.0.51) 🥳
