### ISSUE TITLE
Web Tests are constantly failing for me under MacOS in CI pipeline

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode-test-web#43]
A typical failure can be seen here:

https://dev.azure.com/vscode/vscode-wasm/_build/results?buildId=74201&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=8b9bff53-2841-58c7-68fc-e30c30330fc3

```
> node lib/web/runTests.js

node:events:504
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (node:_http_client:442:9)
    at TLSSocket.emit (node:events:526:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -54,
  code: 'ECONNRESET',
  syscall: 'read'
}
```

**Comment by aeschli** [comment]
I got the same issue after we moved the CI build from gitHub Actions to dev azure.

I now added a `uncaughtException` handler to the test runner (when running `test-web` from the CLI). This seem to help:
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=188358&view=logs&j=4bc49d80-bf2e-5a4d-f40c-10b2635a6a32&t=bece58dd-0f02-58e2-58d7-904a157f0ec5&l=61
The exception is logged and ignore, and didn't seem to cause any trouble.

I think you use the web-test API. So you want to add a `uncaughtException` to your test runner as well.

Where the exception is coming from is hard to say:
https://github.com/nodejs/node/issues/27916
https://github.com/webpack/webpack/issues/15501
https://github.com/mark-wiemer/vscode-helloworld/issues/10

**Comment by aeschli** [comment]
https://github.com/nodejs/node/issues/35824

**Comment by dbaeumer** [comment]
Added the handler.
