### ISSUE TITLE
Pass resolved promise value in web test suite back to parent Node.js runner

### ISSUE THREAD

**Issue by M00TSDNS** [microsoft/vscode-test-web#62]
The microsoft/vscode#167808 ticket appears to be blocked for now..  
But I really want to be able to use some kind of file system access.
This would be possible if the `runTests` call accepted a callback or script path for handling message payloads from `./test/suite/**.ts`.

Alternatively, could I resolve the promise here with a global array of file payloads to write?

https://github.com/microsoft/vscode-test-web/blob/577c16f65e39ef182063d9e40778fc95d113070b/sample/src/web/test/suite/index.ts#L22

That could be wired up to the resolved value of `runTests` in:

https://github.com/microsoft/vscode-test-web/blob/577c16f65e39ef182063d9e40778fc95d113070b/sample/src/web/test/runTest.ts#L19-L25

From there I would have access to the Node fs module so I could write JSON outputs for data testing

**Comment by M00TSDNS** [comment]
This seems quite the challenge ...

https://github.com/microsoft/vscode/blob/2b54ca810fe289f2cabcba75521b004a021b0a79/src/vs/workbench/api/common/extHostExtensionService.ts#L709-L747

Currently it exits with 1 (🛑) or 0 (🆗) but to transfer other information the passed object would need to become a mutable `vscode.*Event` interface - an object with a `status` key that extends a global namespace from inside the worker.

Then we would need to track down each usage and switch it from `event: number` to `event.status as number`.

Can this issue be moved to [microsoft/vscode](https://github.com/microsoft/vscode) to start with, @connor4312?

**Comment by connor4312** [comment]
> the passed object would need to become a mutable vscode.*Event interface - an object with a status key that extends a global namespace from inside the worker.

I don't know which object you're referring to

> This would be possible if the runTests call accepted a callback or script path for handling message payloads from ./test/suite/**.ts.

What is a "message payload"?

**Comment by M00TSDNS** [comment]
> What is a "message payload"?
Currently webviews allow cross window communication using `webview.postMessage`.
The "payload" there is the posted state object. Same thing here for test result.

> I don't know which object you're referring to

I'm suggesting that the `run` function can resolve to a arbitrary variable.
Then the core app and test package can pass it back to the result of `await runTests`.

**Comment by connor4312** [comment]
It sounds like the first ask is for 'ipc' with the running extension. I don't have much interest in doing this at the moment. An extension could already stand up a websocket server pretty easily when running tests and do its communicate through there. That is probably what we'd end up doing under the hood anyway.

> can resolve to a arbitrary variable.

This seems separate from your ask for ipc -- what purpose are you envisioning that this would serve?

**Comment by M00TSDNS** [comment]
> From there I would have access to the Node fs module so I could write JSON outputs for data testing

I will wire something up with IPC I guess..
