### ISSUE TITLE
Vscode-test-web no longer works with VS code insiders

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode-test-web#82]
Our web tests are passing, but on exit they show fail with this error:

```
Test Failed
```

This is coming from this code here:
https://github.com/microsoft/vscode-test-web/blob/0af5b4eb685e7806061b976286a6548fce182f4a/src/index.ts#L204

When debugging that `code` value looks like a set of logs?

![image](https://user-images.githubusercontent.com/19672699/236546224-0fda7eab-6f01-44c3-be0f-1851b46aca23.png)

Is there a dependency mismatch somewhere? I'm honestly not sure where this could have changed. We recently upgraded a bunch of stuff because of dependabot issues, so I'm guessing it's something there, but playwright hasn't changed the calling code in 2 years.

**Comment by rchiodo** [comment]
Ah I think I found the problem. VS code is returning different values now. Change is here:

https://github.com/microsoft/vscode/commit/c4a46ef344946c29b4ad50a85b56e41585aebee2

@bpasero, does a change need to be made in vscode-test-web for your commit?

**Comment by rchiodo** [comment]
We run our tests using insiders, so it explains why this suddenly started failing today.

**Comment by bpasero** [comment]
Sorry for that, I was not aware. Fix coming in https://github.com/microsoft/vscode/pull/181682. I suppose changing the order of parameters so that `code` is again the first should help.
