### ISSUE TITLE
Can't resize the window opened by vscode-web-test 

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode-test-web#9]
from https://github.com/microsoft/vscode-internalbacklog/issues/2414

This is just a little strange, maybe there is a reason for it, but the vscode window does not adapt to resizing the browser window

![image](https://user-images.githubusercontent.com/323878/135177183-2bb8d34c-e3ba-4b83-b689-70fe2c9e6cb7.png)

![image](https://user-images.githubusercontent.com/323878/135177209-740f90b7-5955-4262-9d6d-5b6ed2e24326.png)

**Comment by IronGeek** [comment]
Just my observation... but, if:
- the call to `await page.setViewportSize({ width, height })` is removed ([src/index.ts#222](https://github.com/microsoft/vscode-test-web/blob/main/src/index.ts#L222)), and 
- the `viewport` option is set to `null` when calling `browser.newContext()`: ([src/index.ts#199](https://github.com/microsoft/vscode-test-web/blob/main/src/index.ts#L199)), 

```ts
const context = await browser.newContext({
  viewport: null
});
```
The VS Code window is created using the entire screen as viewport, and it does adapt to resizing the browser window. 
(note: only tested on `Chromium 94.0.4595.0`)

**Comment by aeschli** [comment]
@IronGeek Thanks for the tip!
