### ISSUE TITLE
Suppress activation of the extension

### ISSUE THREAD

**Issue by whitphx** [microsoft/vscode-test-web#96]
I have a case where I want to run only the test code in the web browser environment without activating the extension, i.e. calling the `activate()` function in the entrypoint file,
For example, in a case where there is some runtime-dependent code in `activate()` but I want to run "cleaner" unit tests without calling it.
However, looks like `vscode-test-web` requires the `--extensionDevelopmentPath` option to run the tests and there is no way to bypass it?

**Comment by aeschli** [comment]
`extensionDevelopmentPath` is needed. We use it as that root folder that we mount for VS Code in the browser. The mount is used to access the extension but also the test main file and, if avilable, test data.

Running a test does not activate the extension, unless the test causes that e.g. by invoking a command of the extension.
Also make sure your extension doesn't activate on default (using `*`` as activation point)

I tested this by removing `*`` as activation point from https://github.com/microsoft/vscode-test-web/blob/7858ecd051aabf62576a3cdb05644028abd9d4c8/sample/package.json#L13 and running `npm run sample-tests`

**Comment by whitphx** [comment]
Thank you,

> Also make sure your extension doesn't activate on default (using `*`` as activation point)

Exactly this was the problem in my case.

> I tested this by removing *`` as activation point from https://github.com/microsoft/vscode-test-web/blob/7858ecd051aabf62576a3cdb05644028abd9d4c8/sample/package.json#L13 and running npm run sample-tests`

What do you think I should do to follow this advice in practice, e.g. in CI workflows?
Should I write a utility script to delete the `*`, or are there any clean way?

Thanks!

**Comment by aeschli** [comment]
Can you maybe not give the extension path as `extensionDevelopmentPath`, but a subfolder that contains the test code? Your extension won't be available then.

**Comment by whitphx** [comment]
Thanks, but looks like the test doesn't start running after the browser is launched if `extensionDevelopmentPath` is set as a path other than the root such as `--extensionDevelopmentPath=./dist/web/test`.

fyi, I'm using a shell script like this: https://github.com/whitphx/vscode-emacs-mcx/blob/v0.49.1-pre/scripts/run-web-test.sh
