### ISSUE TITLE
Unable to open files with special characters in the file name

### ISSUE THREAD

**Issue by slavek-kucera** [microsoft/vscode-test-web#97]
I am unable to open files that have special characters in their file name (like ```!#$%&'()+,-.0123456789;=@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_`abcdefghijklmnopqrstuvwxyz{}~``` or `test_utf_8_🧿`) that I use during testing.
I think that the problem is that URIs are not properly encoded and then decoded in places like
https://github.com/microsoft/vscode-test-web/blob/3f0f858ab15cb65ef3c19564b0f5a6910ea9414e/fs-provider/src/fsExtensionMain.ts#L112
and
https://github.com/microsoft/vscode-test-web/blob/3f0f858ab15cb65ef3c19564b0f5a6910ea9414e/src/server/mounts.ts#L35

![image](https://github.com/microsoft/vscode-test-web/assets/53339291/3a03dad6-cff4-4aec-a6c4-340502409df8)

**Comment by aeschli** [comment]
To verify:
- close this repo
- run `yarn && yarn sample`
- this opens vscode in the browser on a test workspace that has folders and files with special characters,
- verify these can be opened.

**Comment by slavek-kucera** [comment]
👍 The fix solves the problem. Thank you.
